export const USER = {
  USER_LOADING: "USER_LOADING",
  USER_SUCCESS: "USER_SUCCESS",
  USER_FAILED: "USER_FAILED",
  USER_FETCH: "USER_FETCH",
  USER_LOGOUT: "USER_LOGOUT"
};

// Alert Constants
export const alert = {
  ALERT_HIDE: "ALERT_HIDE",
  ALERT_SHOW: "ALERT_SHOW"
};
