export const auth = {
  AUTH_START: "AUTH_START",
  AUTH_FAILED: "AUTH_FAILED",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
  AUTH_FETCH_USER: "AUTH_FETCH_USER",
  AUTH_LOGOUT: "AUTH_LOGOUT"
};

// Alert Constants
export const alert = {
  ALERT_HIDE: "ALERT_HIDE",
  ALERT_SHOW: "ALERT_SHOW"
};

// profiles
export const profile = {
  PROFILE_LOADING: "PROFILE_LOADING",
  PROFILE_FAILED: "PROFILE_FAILED",
  PROFILE_FETCH: "PROFILE_FETCH",
  PROFILE_ADD: "PROFILE_ADD",
  PROFILE_UPDATE: "PROFILE_UPDATE",
  PROFILE_DELETE: "PROFILE_DELETE",
  PROFILE_EXP_ADD: "PROFILE_EXP_ADD",
  PROFILE_EXP_DELETE: "PROFILE_EXP_DELETE",
  PROFILE_EDU_ADD: "PROFILE_EDU_ADD",
  PROFILE_EDU_DELETE: "PROFILE_EDU_DELETE"
};

// post
export const post = {
  POST_LOADING: "POST_LOADING",
  POST_FAILED: "POST_FAILED",
  POST_ADD: "POST_ADD",
  POST_UPDATE: "POST_UPDATE",
  POST_DELETE: "POST_DELETE",
  ADD_COMMENT: "ADD_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
  POST_LIKE: "POST_LIKE",
  POST_DISLIKE: "POST_DISLIKE",
  FETCH_SINGLE_POST: "FETCH_SINGLE_POST",
  FETCH_ALL_POSTS: "FETCH_ALL_POSTS",
  FETCH_USER_POSTS: "FETCH_USER_POSTS"
};
