export const auth = {
  AUTH_START: "AUTH_START",
  AUTH_FAILED: "AUTH_FAILED",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_REGISTER_SUCCESS: "AUTH_REGISTER_SUCCESS",
  AUTH_FETCH_USER: "AUTH_FETCH_USER",
  AUTH_LOGOUT: "AUTH_LOGOUT"
};

// Alert Constants
export const alert = {
  ALERT_HIDE: "ALERT_HIDE",
  ALERT_SHOW: "ALERT_SHOW"
};
